stages:
  - test
  # - build
  # - deploy

test eureka:
  stage: test
  image: maven:3.6.0-jdk-8
  script:
    - cd eureka-server
    - mvn test
  artifacts:
    expire_in: 5 hours
    paths:
      - target/*-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8
  only:
    changes:
      - eureka-server/*

test zuul:
  stage: test
  image: maven:3.6.0-jdk-8
  script:
    - cd zuul-gateway
    - mvn test
  artifacts:
    expire_in: 5 hours
    paths:
      - target/*-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8
  only:
    changes:
      - zuul-gateway/*

test auth-service:
  stage: test
  image: maven:3.6.0-jdk-8
  script:
    - cd authentication-service
    - mvn test
  artifacts:
    expire_in: 5 hours
    paths:
      - target/*-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8
  only:
    changes:
      - authentication-service/*

test core-service:
  stage: test
  image: maven:3.6.0-jdk-8
  script:
    - cd core-service
    - mvn test
  artifacts:
    expire_in: 5 hours
    paths:
      - target/*-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8
  only:
    changes:
      - core-service/*

test email-service:
  stage: test
  image: maven:3.6.0-jdk-8
  script:
    - cd email-service
    - mvn test
  artifacts:
    expire_in: 5 hours
    paths:
      - target/*-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8
  only:
    changes:
      - email-service/*

test frontend:
  stage: test
  image: trion/ng-cli-karma:9.1.3
  script:
    - cd frontend
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    expire_in: 5 hours
    paths:
      - coverage/
  tags:
    - angular
    - karma
  only:
    changes:
      - frontend/*