# Spring properties
spring:
  # Replace this eventually with an actual Database!
  datasource:
    url: ${DB_HOST:jdbc:h2:file:./core;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: sa
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: authentication-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: guest
    password: guest
    port: ${RABBIT_PORT:5672}

# Discovery Server Access
eureka:
  datacenter: cloud
  instance:
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULTZONE:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

security:
  jwt:
    token:
      issuer: Aud.io
      secret-key: Y8Mbx7xg61CGpHVJI-uMlyb2RYzESBgGnoffmQUd9GnbSMn0-dH7IBbmHstYb03xAYYPI5nl7FjUqgttUriJiCGw-NY-ciq31e-w-dG0Ps4XRKxcGX_rANbZVJeWfN1MywFiqQ2qOOeQh3SWutprkOhcsaVcErogkRRqIR8H3Q8YN7DCyckBWa0saUvfYQR03_rtHZM1k3aSuNspK0oTTpVTrUfzVk3jF0EulTrjE7QT8g5Td2sB29N1lgSYocgmJ_77_Hlxd8P6KiFDJFi5hynLwi1z-r-v1jxw5zC486K58dJhLlxr2oaw7jNoz_nWHiDiI4OYhO32AWIbV8aw # DO NOT CHANGE!
      expire-length: 1800000 # 30 min in ms
      reset-password-expire-length: 604800000 # 7 days in ms
      activate-account-expire-length: 604800000 # 7 days in ms
      delete-account-expire-length: 604800000 # 7 days in ms
  account-claims:
      users: ""
  lockout:
    threshold: 3

# HTTP Server
server:
  port: 8763

