spring:
  application:
    name: eureka-server

# Configure this Discovery Server
eureka:
  datacenter: cloud
  instance:
    preferIpAddress: false
  client:
    # Not a client, don't register with yourself (unless running
    # multiple discovery servers for redundancy)
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49

server:
  port: 8761