# Spring properties
spring:
  # Replace this eventually with an actual Database!
  datasource:
    url: ${DB_HOST:jdbc:h2:file:./core;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: sa
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: core-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: guest
    password: guest
    port: ${RABBIT_PORT:5672}
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 25MB

# Discovery Server Access
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULTZONE:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

storage:
  location: files/

ffmpeg:
  path: C:\Program Files (x86)\FFmpeg\bin\ffprobe.exe

security:
  jwt:
    token:
      issuer: Aud.io
      secret-key: Y8Mbx7xg61CGpHVJI-uMlyb2RYzESBgGnoffmQUd9GnbSMn0-dH7IBbmHstYb03xAYYPI5nl7FjUqgttUriJiCGw-NY-ciq31e-w-dG0Ps4XRKxcGX_rANbZVJeWfN1MywFiqQ2qOOeQh3SWutprkOhcsaVcErogkRRqIR8H3Q8YN7DCyckBWa0saUvfYQR03_rtHZM1k3aSuNspK0oTTpVTrUfzVk3jF0EulTrjE7QT8g5Td2sB29N1lgSYocgmJ_77_Hlxd8P6KiFDJFi5hynLwi1z-r-v1jxw5zC486K58dJhLlxr2oaw7jNoz_nWHiDiI4OYhO32AWIbV8aw # DO NOT CHANGE!
      expire-length: 1800000 # 30 min in ms

s3:
  bucket:
    name: aud.io1

# HTTP Server
server:
  port: 0

